# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 865bd9a16f1619dc6e1cecce46d62014b54f2b46d7078741ad3d6b9b5be34f7235a3376fa036a670e051e34ef5df25f4d724cea8a4908445e804abd527c5204b

test:
  secret_key_base: 89c50b74f002658b00ffadf8226f4f826ef697fd645afe7c25ac0ef9739ecd9e448932f805209cbf2f34d7106e9ff0dd54f48063e9aab0635f026c238f54b059

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
